#!/usr/bin/env python3
"""Overlay design (ESMFold) vs native backbone, Kabsch-superposed, + summary scatter."""
import numpy as np, matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa

def ca(path, model1_only=False):
    coords=[]; bf=[]; seen=set(); inmodel=True
    for line in open(path):
        if line.startswith('ENDMDL'): inmodel=False
        if model1_only and not inmodel: continue
        if line.startswith('ATOM') and line[12:16].strip()=='CA':
            if line[21] not in ('A',' '): continue
            key=line[21]+line[22:27]
            if key in seen: continue
            seen.add(key)
            coords.append([float(line[30:38]),float(line[38:46]),float(line[46:54])]); bf.append(float(line[60:66]))
    return np.array(coords), np.array(bf)

def kabsch(P,Q):
    n=min(len(P),len(Q)); P,Q=P[:n],Q[:n]
    Pc=P-P.mean(0); Qc=Q-Q.mean(0)
    V,S,Wt=np.linalg.svd(Pc.T@Qc); d=np.sign(np.linalg.det(V@Wt))
    U=V@np.diag([1,1,d])@Wt
    Pa=Pc@U
    rmsd=np.sqrt(((Pa-Qc)**2).sum(1).mean())
    return Pa, Qc, rmsd

# (design file, native file, label, seqID, pLDDT)
cases=[
 ("esmfold_designed/1UBQ_design1.pdb","ref_pdb/1UBQ.pdb","ubiquitin (76aa)",53,93.4),
 ("esmfold_designed/1PGA_design2.pdb","ref_pdb/1PGA.pdb","protein G B1 (56aa) — design2",55,93.6),
 ("esmfold_designed/1PGA_design1.pdb","ref_pdb/1PGA.pdb","protein G B1 (56aa) — design1",62,85.3),
 ("esmfold_designed/1VII_design1.pdb","ref_pdb/1VII.pdb","villin HP36 (36aa)",25,75.6),
]

fig=plt.figure(figsize=(11,9))
for i,(d,n,lab,sid,pl) in enumerate(cases,1):
    P,_=ca(d); Q,_=ca(n, model1_only=True)
    Pa,Qc,rmsd=kabsch(P,Q)
    ax=fig.add_subplot(2,2,i,projection='3d')
    ax.plot(Qc[:,0],Qc[:,1],Qc[:,2],color='0.55',lw=3,label='native backbone')
    col='#1a9850' if rmsd<2 else '#d73027'
    ax.plot(Pa[:,0],Pa[:,1],Pa[:,2],color=col,lw=2,label='ProteinMPNN redesign → ESMFold')
    verdict='self-consistent' if (pl>80 and rmsd<2) else 'borderline'
    ax.set_title(f"{lab}\nseqID {sid}%  ·  pLDDT {pl:.0f}  ·  RMSD {rmsd:.2f} Å  ·  {verdict}",fontsize=9)
    ax.set_xticks([]);ax.set_yticks([]);ax.set_zticks([])
    if i==1: ax.legend(fontsize=7,loc='upper left')
fig.suptitle("Generate → Verify:  redesigned sequences (color) folded back onto the native fold (gray)",
             fontsize=12,fontweight='bold')
fig.tight_layout(rect=[0,0,1,0.96])
fig.savefig("figures/overlay_panel.png",dpi=160)
print("wrote figures/overlay_panel.png")

# summary scatter: seqID vs RMSD, colored by pLDDT
# single source of truth = data_summary.csv (generated by analyze_structures.py)
import csv
rows=[r for r in csv.DictReader(open("data_summary.csv")) if r["stage"]=="generate_verify"]
x=[float(r["seqID_to_native_pct"]) for r in rows]
y=[float(r["CA_RMSD_A"]) for r in rows]
c=[float(r["mean_pLDDT"]) for r in rows]
lab=[r["id"].replace("_design","-d") for r in rows]
fig2,ax=plt.subplots(figsize=(7,5))
sc=ax.scatter(x,y,c=c,cmap="viridis",s=90,edgecolor='k',vmin=70,vmax=95)
for xi,yi,li in zip(x,y,lab): ax.annotate(li,(xi,yi),fontsize=7,xytext=(4,4),textcoords='offset points')
ax.axhline(2.0,ls='--',color='r',lw=1); ax.text(60,2.05,"RMSD = 2 Å pass line",color='r',fontsize=8)
ax.set_xlabel("ProteinMPNN sequence identity to native (%)")
ax.set_ylabel("self-consistency RMSD vs native (Å)")
ax.set_title("Lower RMSD + higher pLDDT = design predicted to keep the fold")
fig2.colorbar(sc,label="ESMFold pLDDT")
fig2.tight_layout(); fig2.savefig("figures/summary_scatter.png",dpi=160)
print("wrote figures/summary_scatter.png")
